In [5]:
from src.data.make_amzn_stock_price_dataset import AMZN_SP
from src.models.lstm_model import LSTM
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from src.utils.utils import get_lstm_model_variance
from src.models.conformal_forcast import ConformalForcast
train_set = AMZN_SP(train=True, in_folder='../data/raw',
                    out_folder='../data/processed')
test_set = AMZN_SP(train=False, in_folder='../data/raw',
                   out_folder='../data/processed')
batch_size = 16
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)

ImportError: cannot import name 'get_lstm_model_variance' from 'src.utils.utils' (/Users/abdulrahman/Documents/DTU/b_thesis_project/uncertainty-quantification/src/utils/utils.py)

In [3]:
np.linspace(0,3,200)

NameError: name 'np' is not defined

In [2]:
model = LSTM(1, 4, 2, 0.5)
model.load_state_dict(torch.load("../models/trained_lstm_amzn.pt"))
model.eval()
model = torch.nn.DataParallel(model).cpu()

In [3]:
cmodel = ConformalForcast(model, test_loader, 0.1)

[[[-0.8733053 ]
  [-0.8750514 ]
  [-0.8782581 ]
  [-0.8732369 ]
  [-0.86879766]
  [-0.86983615]
  [-0.87365913]]

 [[-0.8750514 ]
  [-0.8782581 ]
  [-0.8732369 ]
  [-0.86879766]
  [-0.86983615]
  [-0.87365913]
  [-0.8812822 ]]

 [[-0.8782581 ]
  [-0.8732369 ]
  [-0.86879766]
  [-0.86983615]
  [-0.87365913]
  [-0.8812822 ]
  [-0.87379605]]

 [[-0.8732369 ]
  [-0.86879766]
  [-0.86983615]
  [-0.87365913]
  [-0.8812822 ]
  [-0.87379605]
  [-0.87570184]]

 [[-0.86879766]
  [-0.86983615]
  [-0.87365913]
  [-0.8812822 ]
  [-0.87379605]
  [-0.87570184]
  [-0.8757817 ]]

 [[-0.86983615]
  [-0.87365913]
  [-0.8812822 ]
  [-0.87379605]
  [-0.87570184]
  [-0.8757817 ]
  [-0.8714338 ]]

 [[-0.87365913]
  [-0.8812822 ]
  [-0.87379605]
  [-0.87570184]
  [-0.8757817 ]
  [-0.8714338 ]
  [-0.86294335]]

 [[-0.8812822 ]
  [-0.87379605]
  [-0.87570184]
  [-0.8757817 ]
  [-0.8714338 ]
  [-0.86294335]
  [-0.8658077 ]]

 [[-0.87379605]
  [-0.87570184]
  [-0.8757817 ]
  [-0.8714338 ]
  [-0.86294335]
  [-0.86